version: 2

sources:
  - name: qwt_raw
    database: "{{env_var('DBT_SOURCEDB','QWTANALYTICS_DEV')}}"
    schema: "{{env_var('DBT_STAGESCHEMA','RAW_DEV')}}"
    tables:
       - name: customers
       - name: orders
       - name: OrderDetails
       - name: Products
       - name: EMPLOYEE
       - name: Shipments
       - name: SUPLIERS_XML

